In [2]:
import torch
import numpy as np
A = torch.rand(2,3,4)
sort = torch.tensor([[[1,3,0,2]]])
A1,A2 = A[0,:,:],A[1, : ,:]
A1_1,A1_2 = A1[:,0],A1[:,2]
A,A1_1
B = torch.zeros_like(A)
B[1,:,0] = A[1,:,1]
B

tensor([[[0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.6458, 0.0000, 0.0000, 0.0000],
         [0.7968, 0.0000, 0.0000, 0.0000],
         [0.5712, 0.0000, 0.0000, 0.0000]]])

In [3]:
def index_select(Tensor,sort):
    if Tensor.shape[2] != sort.shape[2]:
        return False
    tensor1 = torch.zeros_like(Tensor)
    sort =sort.squeeze().numpy()#[1, 3, 0, 2]
    print(sort)
    for i,data1 in enumerate(Tensor):
        #tensor([[0.0267, 0.1841, 0.3536, 0.8287],
        #[0.7979, 0.7503, 0.0724, 0.1624],
        #[0.9605, 0.5758, 0.3361, 0.8355]])
        for index,sort_num in enumerate(sort):
            tensor1[i,:,index] = Tensor[i,:, sort_num]
    return  tensor1
tensor1 = index_select(A,sort)
A,tensor1

[1 3 0 2]


(tensor([[[0.7603, 0.3164, 0.0646, 0.9082],
          [0.6739, 0.9924, 0.4831, 0.8318],
          [0.6027, 0.5403, 0.8244, 0.5409]],
 
         [[0.0213, 0.6458, 0.1598, 0.4550],
          [0.8655, 0.7968, 0.0680, 0.1946],
          [0.1817, 0.5712, 0.7926, 0.1893]]]),
 tensor([[[0.3164, 0.9082, 0.7603, 0.0646],
          [0.9924, 0.8318, 0.6739, 0.4831],
          [0.5403, 0.5409, 0.6027, 0.8244]],
 
         [[0.6458, 0.4550, 0.0213, 0.1598],
          [0.7968, 0.1946, 0.8655, 0.0680],
          [0.5712, 0.1893, 0.1817, 0.7926]]]))